# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20170425_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.ManyToManyField(null=True, related_name='rates', through='store.RateUserBook', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='readStatus',
            field=models.ManyToManyField(null=True, related_name='status', through='store.BookState', to=settings.AUTH_USER_MODEL),
        ),
    ]
